### ISSUE TITLE
Report results inconsistent w/ at-a-glance line and w/ Summary grid

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#284] opened 2015-08-07 19:28 UTC
1. Browse to https://omnim2m.net, Chrome 43, Win 8.1, login as Dave, select Sempra
2. Notice time filter set to Last 24 hrs, device scope as all
3. Notice Summary Line showing 4 devices as having reported w/in last 24 hrs (and this is confirmed by Summary (renamed Last Report) grid
4. Run report and view report

Expected - 4 entries in report

Actual - no entries in report

Question - does report use local time for device or local time for server?
![capture - inconsistency landing page view](https://cloud.githubusercontent.com/assets/12534533/9144112/b04f645a-3cff-11e5-804c-254270fbd1ab.PNG)
![capture - inconsistency report view](https://cloud.githubusercontent.com/assets/12534533/9144115/b46bf47c-3cff-11e5-9cc0-57ddb1e5e3de.PNG)

**Comment by davroth** [comment] 2015-09-11 14:18
Ran this again today and saw same inconsistency between "Reported within 24 Hours" (9) in "at a glance" and the report. (nothing shown in either tab of spreadsheet). The "Last Report" grid agreed with the "at a glance" number.

**Comment by peters95** [comment] 2015-10-12 16:55
+1

**Comment by peters95** [comment] 2015-10-28 21:48
Cannot reproduce this issue.. Dave are you able to repro this?

**Comment by davroth** [comment] 2015-10-28 22:25
just repro'ed using steps above @ 3:20 PM PDT (12:20 hawaii time?) 
![capture - report inconsistency](https://cloud.githubusercontent.com/assets/12534533/10805015/0c64fe3a-7d88-11e5-8bd4-8003c5f02db8.PNG)
on Omnistaging site, Windows 10, chrome browser, logged in as dave@omnim2m.com, selected Sempra landing page and clicked green report icon.
Picture below shows use of default device time filters.

**Comment by peters95** [comment] 2015-11-04 20:48
For ScenarioId = 1 ("Trap") reports use the following stored procedure:

sp_ReportMessageDetail

It will pass in the list of devices and the number of days to report from.
It will run for the first sheet the following SQL:

```
select 
    CustomerUnitNumber as 'Device Name'
    ,DataString1 as 'State'
    ,str(cast(cast(Cast (BatteryLevel as float) / 10 as float) as varchar(max)),10,1)   as 'Voltage' -- Cast((@CurrentGallons/@maxGallons)*100 as varchar(50))
    ,IIF(SignalStrength = 0,'N / A',str(SignalStrength)) as 'Signal Strength'
    ,dbo.FormatDate(MessageDate,'mm/dd hh:nn') as 'Time'

 from DMResolved WITH (NOLOCK)

    where  DeviceId  in (select Item from SplitInts(@Ids2)) and
    MessageDate >  DATEADD(day, - @NumberOfDays2, GETDATE())
    Order by MessageDate Desc
```

**Comment by peters95** [comment] 2015-11-04 20:50
report parameter input:

sp_ReportMessageDetail @Ids = 89,12,82,20,91,56,96,21,16,9,94,84,127,25,126,125,124,120,24,41,122,121,23,112,114,52,49,54,48,71,14,64,69,67,65,110,108,4,3,2,1,7,83,79,45,81,47,44,88,63,32,75,86,80,31,34,51,119,107,92,73,19,8,26,113,66,116,18,115,109,93,95,15,33,87,85,111,77,5,17,10,42,46,101,99,28,53,27,55,29,61,6,97,103,105,68,70,72,74,76,78,90,98,100,102,104,106,117,118,30,35,36,37,38,39,40,43,13,57,58,59,60,62,@NumberOfDays = 1,@ScenarioId = 1

**Comment by peters95** [comment] 2015-11-04 21:04
On the webpage the number of devices that have reported come from:

[sp_GetScenarioSummaryHighlights]

This is running SQL:

```
SELECT 
    @AlertCount = Count(Alerts.Id)
    FROM Alerts
    where 

        StatusId > 0  and
        Alerts.IsActive = 1 and
        SiteId In (select Id from dbo.GetChildSites(@SiteID))
         and InsertDate >= dateadd(day,-1*@NewNumberOfDays,getdate())

     select @DevicesCount = count(ID) from DeviceInventory 
            where SiteId In (select Id from dbo.GetChildSites(@SiteID))
            and DeviceInventory.IsActive =1

    select @DevicesReportingCount = count(ID) from DMResolvedLatest 
            where SiteId In (select Id from dbo.GetChildSites(@SiteID))
            and InsertDate >= dateadd(day,-1,getdate())



  select  
        @AlertCount as [Highlights.ActiveAlerts]
        , @DevicesReportingCount as [Highlights.DevicesReporting]
        , @DevicesCount as [Highlights.DeviceCount]
```

**Comment by peters95** [comment] 2015-11-04 21:05
Given the only difference found between the two SQL is the DMResolved vs DMResolvedLatest I will change reporting query to use same DMResolvedLatest to match webpage.. Updating report SQL and closing github bug

**Closed as completed by peters95** 2015-11-04 21:05 UTC
Labels: bug, Priority MEDIUM

**Comment by peters95** [comment] 2015-11-04 21:14
I  updated MessageDate on both queries to use same date. that was also causing some differences. Counts now match at 15.
