### ISSUE TITLE
No circular graph is after saving rules (whether or not rules were saved

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#129] opened 2015-05-28 23:28 UTC
Steps to reproduce:
1) Log into Omni
2) Go to Tanks
3) Open the rules up
4) Hit the "Save rules" button
5) Observe the "%" section on the table any device

Occurs:
There is nothing left in the % section of the graph.
Before Save
![before low fuel](https://cloud.githubusercontent.com/assets/12438510/7873361/4b9f54a6-0556-11e5-8470-69d2341580c4.png)

After Save
![after low fuel](https://cloud.githubusercontent.com/assets/12438510/7873362/4f81ffec-0556-11e5-9739-07ea9c03f613.png)

(Small side note, originally thought this had to do with low fuel and came up with the idea that we might want to make the blue that shows the remaining fuel turn red when the fuel drops below the alert threshold.)

**Comment by patrickomni** [comment] 2015-06-03 02:31
Probably a dupe of the other related to this

**Comment by christopherdude** [comment] 2015-06-04 09:21
Added the script ReloadApplicationJs key to the MyModalRulesSettings_RulesSaved event.  Now reloads the application.js so that the script initialization for circle graphs reloads upon ajax callbacks.

**Comment by davroth** [comment] 2015-06-04 17:20
fixed

**Closed as completed by davroth** 2015-06-04 17:20 UTC
Labels: bug
