### ISSUE TITLE
Sempra landing page - what does "Total Messages" mean?

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#173] opened 2015-06-14 16:51 UTC
The "Total Messages" box number increments (just went from 30 to 31), but it is difficult to reconcile that movement w/ other data shown on the screen - the alerts column (designated by the triangular icon in the Summary grid) shows a total of 36 messages - and w/ Caldera site which does not show any messages since 12-Jun using this URL - http://calderadev.server289.com/trapnet/show_reports.php?&start=0&sensor=&gateway=

**Comment by davroth** [comment] 2015-06-15 18:21
Reisner messages box doesn't seem to reconcile w/ grid below - count is zero in messages box while grid shows a recent message:

![capture - message count](https://cloud.githubusercontent.com/assets/12534533/8167056/995d7ee0-1350-11e5-8825-e80df69243bd.PNG)

**Comment by christopherdude** [comment] 2015-06-16 20:04
I believe this to be correct, but misunderstood.  I'm going to let Pat answer this one, as I don't think it's a show-stopper.  MESSAGES are (what I believe) alerts at StatusID=1, where ALERTS are StatusID=2.

**Comment by davroth** [comment] 2015-06-17 14:12
This is not showstopper, but definitely needs to be understood, and there still appears to be a problem w/ Sempra MESSAGES box - on 16-Jun around 10 PM, the MESSAGES counter was 43. On the morning of 17-Jun, Omni was displaying 6 new messages w/ no new Alerts, but the MESSAGES counter had only incremented to 47.

**Comment by patrickomni** [comment] 2015-06-22 23:25
Duplicate of #176

**Closed as completed by patrickomni** 2015-06-22 23:25 UTC
Labels: help wanted
