### ISSUE TITLE
Edit User Button Loading Screen Freeze

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#22] opened 2015-05-12 17:26 UTC
When you click the edit user button, the loading bar appears and freezes - Logged with iPhone 5S

**Comment by patrickomni** [comment] 2015-05-18 19:32
This is a blocking issues.  Assigning to Chris and sending an SMS/Email

Chris,
1. Go to Emp Page
2. Select Edit on a customer

Result
![image](https://cloud.githubusercontent.com/assets/12114620/7688524/ee09da5e-fd59-11e4-8752-1452abbdf351.png)

**Comment by christopherdude** [comment] 2015-05-18 20:13
This is caused by Fridge account(s).  That fridge account has a userRoleId=4.  But my UserEditableRow.ascx doesn't know of a value for that.. only these:

```
            <asp:ListItem Text="Basic User" Value="2" />
            <asp:ListItem Text="OmniAdmin" Value="0" />
            <asp:ListItem Text="Reseller" Value="1" />
            <asp:ListItem Text="Account Admin" Value="3" />
```

That will solve the problem - if we add a value of 4 in there.. but I'm not sure if A) I'm just missing a value, or B) one of the above is wrong

**Comment by patrickomni** [comment] 2015-05-18 20:39
This was an issue with the back end.  This has been fixed (and will work without a new build)

**Comment by CaseyDengler** [comment] 2015-05-18 23:44
Can't find problem on my end, closing.

**Closed as completed by CaseyDengler** 2015-05-18 23:44 UTC
