### ISSUE TITLE
Website freezes in iPad safari browser

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#113] opened 2015-05-23 13:12 UTC
Website freezes when changing the distributor list from drop down.

Before changing: 
![photo2](https://cloud.githubusercontent.com/assets/12525836/7784215/151fd42a-017b-11e5-813d-ebb160db8df9.jpg)

After change: 

![photo1](https://cloud.githubusercontent.com/assets/12525836/7784217/39746098-017b-11e5-85c9-931f50f13a71.jpg)

Steps:
1) Open safari browser in Ipad
2) Log into Omnistaging.azurewebsites.net
3) Go to Reisner Distributor, Inc / Reisner Client  
4) Click to change the distributor list from drop down.

**Comment by patrickomni** [comment] 2015-06-02 19:23
Find this dupe and close

**Comment by CaseyDengler** [comment] 2015-06-03 00:01
Duplicate of issue #108

**Closed as completed by CaseyDengler** 2015-06-03 00:01 UTC
Labels: bug, duplicate
