### ISSUE TITLE
Reisner Fuel Level too high in 30 Day Graph

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#184] opened 2015-06-18 20:05 UTC
This may be a duplicate.

When viewing the Reisner 30 Graph, level for the period in early June show the tank plateaued at 100%.

I believe the reason for this is as follows:
At that time, we initialized a new piece of CalAmp hardware to test GeoLocation for potential use at the Pipeline Company as an Asset Tracker. The device was battery powered and the battery expired coincident with the data in the graph returning to normal. Since this device was not actually connected to a fuel sensor, it reported a measurement level of 13V, way above what a sensor would report (0V - 5V). Since this device reported through the same server as the fuel sensor, it was stored int he database with a scenario Id equal to Fuel Measurement since it uses the same stored procedure to insert the data. It would appear that even though this new device was not registered in the system, it's data was merged with the real Reisner device and thus, the display is incorrect.

**Comment by patrickomni** [comment] 2015-06-22 23:18
This is not a bug.   They actually filled the tank over memorial day and no one drew on it.

**Comment by CaseyDenglerOmni** [comment] 2015-06-23 20:51
Not a bug, closing.

**Closed as completed by CaseyDenglerOmni** 2015-06-23 20:51 UTC
Labels: bug
