### ISSUE TITLE
'Users' Is Broken

### ISSUE THREAD

**Issue by danomni** [patrickomni/omnimobileserver#25] opened 2015-05-12 17:31 UTC
Under 'Add Account', 'Users' Tab is Broken

**Comment by patrickomni** [comment] 2015-05-15 19:07
Can you give more detail?  I think there is a intuitiveness to the design here that isn't obvious.   

Actaully Chris, just auto-save a blank, then update it to active=0 if they cancel.  That way the users tab will work.

**Comment by CaseyDengler** [comment] 2015-05-17 19:52
I believe issue #14 should have some more detail in one of my commets

**Comment by christopherdude** [comment] 2015-05-19 08:14
What I did was, add a tooltip that says they can't add users until they save.  BUT, there's a new problem.  In the sp_SetAccountsById sproc, it's supposed to return to me the new account created, but it's returning an empty dataset.  So this one is back to you, Pat.  

To repro, create a new account, and save.  Place a breakpoint on the SaveAccount method within AccountFactory.cs (line 108 at the time of this logging of bug).

**Comment by danomni** [comment] 2015-05-19 16:30
Just added a new account 'Charlie Parker', with permission of a reseller and after clicking 'Save User, the screen remained the same with fields still open for me to modify the account. When I clicked 'Save' at the bottom of the screen, it refreshed and took me back to the 'Account' tab and now the 'User' tab has a circle with a line through it (no symbol). When I log back out and in with Charlie Parker I have 'Omni admin' permissions and not reseller. Further, the 'User' tab under 'Add Account' still has a 'No Symbol' icon when I hover over it.

**Comment by patrickomni** [comment] 2015-05-19 19:11
Took a deep dive here (which resulted in the email about error handling).    Most of the work is done but I am now getting a javascript error and since javascript is for monkey's, I'm assigning the remaining work to Chris.

Chris: Steps to Reproduce
On employee page select Test account
Go to the users tab
fill in relevant data
Click Save User

Unhandled exception at line 6, column 28143 in http://localhost:8329/Scripts/WebForms/MsAjax/MicrosoftAjaxWebForms.js

0x800a138f - JavaScript runtime error: Unable to get property 'PRM_ParserErrorDetails' of undefined or null reference

**Comment by christopherdude** [comment] 2015-05-22 04:07
We may have this fixed with a new fix already put in.  I'm waiting to hear from Pat on this.

**Comment by patrickomni** [comment] 2015-05-22 07:00
Fixed

**Comment by CaseyDengler** [comment] 2015-05-28 22:39
Almost. The information that was filled into one box is carried over, auto filling any other new user information. Instead, when the user's information has been saved or cancelled (maybe not cancelled?), the next set of boxes for adding a new user are empty. This issue carries over into other accounts until the user logs off or impersonates someone.

**Comment by CaseyDengler** [comment] 2015-05-28 23:09
Found out that the reason I kept this issue open is already listed in issue #11 so there is no reason to keep this one around.

**Closed as completed by CaseyDengler** 2015-05-28 23:09 UTC
