### ISSUE TITLE
Setting for Device(s) at site Y-Hata International not saving for all Devices.

### ISSUE THREAD

**Issue by Rahul-Silicon** [patrickomni/omnimobileserver#110] opened 2015-05-23 11:40 UTC
Settings for devices by site (site Y-Hata International) are not saving same rule for all the device at site Y-Hata International. Try to change or modify the rules for devices at site and click on the save rule button.

Again open setting for the site and settings for devices and analyse the result. (Both have different rule)

Settings for Device at site:

![image](https://cloud.githubusercontent.com/assets/12525836/7783836/0ac923f8-016e-11e5-9121-ed08a5d86a2f.png)

Settings for device: 

![image](https://cloud.githubusercontent.com/assets/12525836/7783840/3b999e54-016e-11e5-9610-94c60419e905.png)

Steps:
1) Log into Omnistaging.azurewebsites.net
2) Go to Omni Refrigeration / Fridge Sample 
3) Click on Setting for Device(s) at site Y-Hata International 
4) Modify and set the rule for devices at site and hit save button.
5) Again open the setting for site and setting for devices and analyse the result.

**Comment by CaseyDengler** [comment] 2015-06-02 21:30
We might need a more intuitive way for people to see the difference between the site rules and the device rules.

Ideally, we want the rules for all devices to fall under the site rules unless the user specifies otherwise. As of now, there isn't a way for the user to specify which rules to use, let alone know which rules are in action.

Overall, we might need some more work on the UI for the rules.

**Comment by davroth** [comment] 2015-06-04 17:16
1. Browse to staging site using IE 11, Windows 8.1, log in as patrick, select Test Fridge
2. Click global rules icon for "latest device status", see expected popup about no results, select Test Fridge user, click save rule, and get "success" bubble
3. Click Fridge 2, see expected popup about no rules for this device, select Patrick Fridge user, click save rule, and get "success" bubble
4. Click global rules icon again to review rule to alert Test Fridge user

Expected: rule still there

Actual: popup about no results

Returning to Fridge 2 at this point shows that rule still there; if I re-create the rule at the global level, it successfully saves, but then when I return to Fridge 2, that rule is gone...

**Comment by davroth** [comment] 2015-06-08 13:35
Closing this because it's duplicate of #133

**Closed as completed by davroth** 2015-06-08 13:35 UTC
Labels: bug, duplicate
